/**
 * Phase 12 - Advanced HSE Analytics, Executive Intelligence & Reporting
 * Authoritative Server-Side Analytics Calculation Engine
 */

import {
  AnalyticsFilterOptions,
  AnalyticsOverviewResponse,
  KPICardData,
  MetricChange,
  SifDistributionMetrics,
  RiskDistributionMetrics,
  PrecursorMetricItem,
  BarrierMetricItem,
  IogpRuleMetricItem,
  SiteAnalyticsItem,
  ActivityAnalyticsItem,
  PatternAnalyticsMetrics,
  ReviewAnalyticsMetrics,
  CapaAnalyticsMetrics,
  AlertAnalyticsMetrics,
  TimeSeriesPoint,
  HeatmapCell,
  DataQualitySummary,
  ManagementReportSummary,
  MetricDefinition,
  ANALYTICS_SCHEMA_VERSION,
  METRIC_DEFINITION_VERSION,
  ReviewedStatePolicy,
} from './analyticsTypes.ts';

import { dataStore, ReportRecord, SITES, ACTIVITIES } from './dataStore.ts';
import { reviewStore } from './reviewStore.ts';
import { actionStore } from './actionStore.ts';
import { alertStore } from './alertStore.ts';
import { patternStore } from './patternDiscoveryService.ts';
import { riskAggregationService } from './riskAggregationService.ts';

export const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  TOTAL_REPORTS: {
    metric_id: 'TOTAL_REPORTS',
    display_name: 'Total Observation & Incident Reports',
    definition: 'Total count of safety reports matching current organizational scope and temporal filters.',
    authoritative_source: 'SUCHAK Safety Reports Store (dataStore.reports)',
    calculation_formula: 'COUNT(reports WHERE in_filter_scope = true)',
    unit: 'reports',
    is_rate: false,
    notes: 'Includes all Unsafe Acts, Unsafe Conditions, Near-Misses, and Incidents.',
  },
  SIF_POTENTIAL: {
    metric_id: 'SIF_POTENTIAL',
    display_name: 'SIF Potential Reports',
    definition: 'Count of reports classified as Serious Injury or Fatality (SIF) Potential under active reviewed state policy.',
    authoritative_source: 'Phase 4 AI Evaluation & Phase 9 Human Review Store',
    calculation_formula: 'COUNT(reports WHERE classification = "SIF_POTENTIAL")',
    unit: 'reports',
    is_rate: false,
    notes: 'Default policy prioritizes latest human-verified review record over initial AI classification.',
  },
  HIGH_CRITICAL_PRIORITY: {
    metric_id: 'HIGH_CRITICAL_PRIORITY',
    display_name: 'High & Critical Risk Reports',
    definition: 'Reports evaluated as High or Critical priority by the Phase 6 Risk Prioritization Engine.',
    authoritative_source: 'Phase 6 Risk Intelligence Service',
    calculation_formula: 'COUNT(reports WHERE priority IN ("HIGH", "CRITICAL"))',
    unit: 'reports',
    is_rate: false,
    notes: 'Calculated using energy magnitude, barrier degradation, and exposure duration.',
  },
  RECURRING_PATTERNS: {
    metric_id: 'RECURRING_PATTERNS',
    display_name: 'Active Recurring Patterns',
    definition: 'Detected precursor clusters matching statistical support and unique-date criteria.',
    authoritative_source: 'Phase 8 Precursor Pattern Store',
    calculation_formula: 'COUNT(patterns WHERE status IN ("EMERGING", "PERSISTENT"))',
    unit: 'patterns',
    is_rate: false,
    notes: 'Requires minimum 3 report members across at least 2 distinct calendar dates.',
  },
  OPEN_ACTIONS: {
    metric_id: 'OPEN_ACTIONS',
    display_name: 'Open CAPA Actions',
    definition: 'Corrective, preventive, and containment actions currently in non-terminal workflow states.',
    authoritative_source: 'Phase 10 Action / CAPA Store',
    calculation_formula: 'COUNT(actions WHERE status NOT IN ("CLOSED", "CANCELLED"))',
    unit: 'actions',
    is_rate: false,
    notes: 'Encompasses OPEN, ASSIGNED, IN_PROGRESS, COMPLETED, and VERIFICATION_REQUIRED states.',
  },
  OVERDUE_ACTIONS: {
    metric_id: 'OVERDUE_ACTIONS',
    display_name: 'Overdue Actions',
    definition: 'Active open actions whose milestone completion target (due_at) is prior to current time.',
    authoritative_source: 'Phase 10 Action / CAPA Store',
    calculation_formula: 'COUNT(actions WHERE is_overdue = true)',
    unit: 'actions',
    is_rate: false,
    notes: 'Actions in CLOSED or CANCELLED status are excluded from overdue calculations.',
  },
  PENDING_REVIEWS: {
    metric_id: 'PENDING_REVIEWS',
    display_name: 'Pending HSE Reviews',
    definition: 'Reports awaiting human HSE specialist review or verification of AI safety outputs.',
    authoritative_source: 'Phase 9 Human Review Queue Store',
    calculation_formula: 'COUNT(reviews WHERE status IN ("QUEUED", "ASSIGNED", "IN_REVIEW", "NEEDS_MORE_REVIEW"))',
    unit: 'reviews',
    is_rate: false,
    notes: 'Ensures human-in-the-loop oversight on all high-consequence reports.',
  },
  ACTIVE_ALERTS: {
    metric_id: 'ACTIVE_ALERTS',
    display_name: 'Active Operational Alerts',
    definition: 'Non-dismissed, non-resolved notification signals generated by deterministic detection rules.',
    authoritative_source: 'Phase 11 Alerts & Escalation Store',
    calculation_formula: 'COUNT(alerts WHERE status IN ("UNREAD", "READ", "ACKNOWLEDGED"))',
    unit: 'alerts',
    is_rate: false,
    notes: 'Alerts function as workflow signals and do not alter underlying report risk ratings.',
  },
  COMPLETION_RATE: {
    metric_id: 'COMPLETION_RATE',
    display_name: 'CAPA Completion Rate',
    definition: 'Ratio of verified or closed actions to total eligible (non-cancelled) actions.',
    authoritative_source: 'Phase 10 Action / CAPA Store',
    calculation_formula: '(closed_actions + verified_actions) / (total_actions - cancelled_actions) * 100',
    unit: '%',
    is_rate: true,
    notes: 'Demonstrates corrective action lifecycle resolution.',
  },
};

export class AnalyticsService {
  private cache: Map<string, { data: any; expiry: number }> = new Map();
  private cacheTtlMs = 15000; // 15s in-memory cache

  /**
   * Helper: resolves date ranges for current and previous equivalent period
   */
  private resolveTimeWindows(options: AnalyticsFilterOptions): {
    currentStart: Date | null;
    currentEnd: Date;
    previousStart: Date | null;
    previousEnd: Date | null;
    preset: AnalyticsFilterOptions['time_window'];
  } {
    const preset = options.time_window || '30d';
    const now = new Date();
    let currentEnd = options.end_date ? new Date(options.end_date) : now;
    let currentStart: Date | null = null;
    let durationMs = 0;

    if (preset === '7d') {
      durationMs = 7 * 86400000;
      currentStart = new Date(currentEnd.getTime() - durationMs);
    } else if (preset === '30d') {
      durationMs = 30 * 86400000;
      currentStart = new Date(currentEnd.getTime() - durationMs);
    } else if (preset === '90d') {
      durationMs = 90 * 86400000;
      currentStart = new Date(currentEnd.getTime() - durationMs);
    } else if (preset === '1y') {
      durationMs = 365 * 86400000;
      currentStart = new Date(currentEnd.getTime() - durationMs);
    } else if (preset === 'custom' && options.start_date) {
      currentStart = new Date(options.start_date);
      durationMs = currentEnd.getTime() - currentStart.getTime();
    } else {
      // 'all'
      currentStart = null;
    }

    let previousStart: Date | null = null;
    let previousEnd: Date | null = null;

    if (currentStart && durationMs > 0) {
      previousEnd = new Date(currentStart.getTime());
      previousStart = new Date(currentStart.getTime() - durationMs);
    }

    return {
      currentStart,
      currentEnd,
      previousStart,
      previousEnd,
      preset,
    };
  }

  /**
   * Filter reports strictly by organization and filters
   */
  private filterReports(
    allReports: ReportRecord[],
    options: AnalyticsFilterOptions,
    start: Date | null,
    end: Date
  ): ReportRecord[] {
    const orgId = options.organization_id || 'oil-india-demo';

    return allReports.filter((r) => {
      // 1. Organization boundary
      if (r.organization_id && r.organization_id !== orgId) return false;

      // 2. Temporal boundary
      if (start) {
        const rTime = new Date(r.report_datetime || r.created_at).getTime();
        if (rTime < start.getTime() || rTime > end.getTime()) return false;
      }

      // 3. Site filter
      if (options.site_id && options.site_id !== 'ALL') {
        if (r.site_id !== options.site_id && r.site?.code !== options.site_id) return false;
      }

      // 4. Activity filter
      if (options.activity_id && options.activity_id !== 'ALL') {
        if (r.activity_id !== options.activity_id && r.activity?.code !== options.activity_id) return false;
      }

      // 5. Report type filter
      if (options.report_type && options.report_type !== 'ALL') {
        const normTarget = options.report_type.toLowerCase().replace(/[-_ ]/g, '');
        const normType = r.report_type.toLowerCase().replace(/[-_ ]/g, '');
        if (normType !== normTarget) return false;
      }

      // 6. SIF status filter
      if (options.sif_status && options.sif_status !== 'ALL') {
        const isSif =
          r.latest_analysis?.classification === 'SIF_POTENTIAL' ||
          r.latest_analysis?.sif_potential === true;
        if (options.sif_status === 'SIF_POTENTIAL' && !isSif) return false;
        if (options.sif_status === 'NON_SIF_POTENTIAL' && isSif) return false;
      }

      // 7. Risk priority filter
      if (options.risk_priority && options.risk_priority !== 'ALL') {
        const prio = r.latest_risk_assessment?.priority || r.latest_analysis?.priority;
        if (prio !== options.risk_priority) return false;
      }

      return true;
    });
  }

  /**
   * Safe comparison calculation (handles zero previous without division by zero or Infinity)
   */
  public calculateComparison(current: number, previous: number): MetricChange {
    const diff = current - previous;

    if (previous === 0) {
      if (current === 0) {
        return {
          current_value: current,
          previous_value: previous,
          absolute_change: 0,
          percentage_change: 0,
          direction: 'UNCHANGED',
          label: '0 in both periods',
        };
      }
      return {
        current_value: current,
        previous_value: previous,
        absolute_change: diff,
        percentage_change: null,
        direction: 'NEW_BASELINE',
        label: 'No prior-period baseline',
      };
    }

    const pct = Math.round((diff / previous) * 1000) / 10;
    const direction = diff > 0 ? 'INCREASE' : diff < 0 ? 'DECREASE' : 'UNCHANGED';
    const label = `${diff >= 0 ? '+' : ''}${pct.toFixed(1)}% vs prior period`;

    return {
      current_value: current,
      previous_value: previous,
      absolute_change: diff,
      percentage_change: pct,
      direction,
      label,
    };
  }

  /**
   * Determine effective SIF classification taking into account reviewed-state policy
   */
  private getEffectiveClassification(
    report: ReportRecord,
    policy: ReviewedStatePolicy = 'LATEST_REVIEWED'
  ): {
    classification: 'SIF_POTENTIAL' | 'NON_SIF_POTENTIAL' | 'NEEDS_REVIEW';
    isHumanConfirmed: boolean;
    isHumanCorrected: boolean;
  } {
    const orgId = report.organization_id || 'oil-india-demo';
    const humanReview = reviewStore.getReviewedSafetyRecord(report.id, orgId);

    if (policy === 'LATEST_REVIEWED' && humanReview) {
      const isConfirmed = humanReview.corrections_applied.length === 0;
      const isCorrected = humanReview.corrections_applied.length > 0;
      return {
        classification: humanReview.classification,
        isHumanConfirmed: isConfirmed,
        isHumanCorrected: isCorrected,
      };
    }

    const raw = report.latest_analysis?.classification || 'NEEDS_REVIEW';
    return {
      classification: raw,
      isHumanConfirmed: false,
      isHumanCorrected: false,
    };
  }

  /**
   * Main: Generates comprehensive Analytics Overview
   */
  public async getOverview(options: AnalyticsFilterOptions = {}): Promise<AnalyticsOverviewResponse> {
    const orgId = options.organization_id || 'oil-india-demo';
    const cacheKey = `${orgId}:${JSON.stringify(options)}:${ANALYTICS_SCHEMA_VERSION}`;

    const cached = this.cache.get(cacheKey);
    if (cached && cached.expiry > Date.now()) {
      return cached.data;
    }

    const windows = this.resolveTimeWindows(options);
    const allReports = Array.from(new Set(dataStore.reports.values()));

    // Current period reports
    const currentReports = this.filterReports(
      allReports,
      options,
      windows.currentStart,
      windows.currentEnd
    );

    // Previous equivalent period reports
    const previousReports = windows.previousStart
      ? this.filterReports(
          allReports,
          options,
          windows.previousStart,
          windows.previousEnd!
        )
      : [];

    const policy = options.reviewed_state_policy || 'LATEST_REVIEWED';

    // 1. SIF Distribution
    let sifCount = 0;
    let nonSifCount = 0;
    let needsReviewCount = 0;
    let humanConfirmedCount = 0;
    let humanCorrectedCount = 0;

    for (const r of currentReports) {
      const eff = this.getEffectiveClassification(r, policy);
      if (eff.classification === 'SIF_POTENTIAL') sifCount++;
      else if (eff.classification === 'NON_SIF_POTENTIAL') nonSifCount++;
      else needsReviewCount++;

      if (eff.isHumanConfirmed) humanConfirmedCount++;
      if (eff.isHumanCorrected) humanCorrectedCount++;
    }

    // Previous period SIF count for comparison
    let prevSifCount = 0;
    for (const r of previousReports) {
      const eff = this.getEffectiveClassification(r, policy);
      if (eff.classification === 'SIF_POTENTIAL') prevSifCount++;
    }

    const totalAnalyzed = currentReports.filter((r) => r.latest_analysis).length;
    const sifRatePct = totalAnalyzed > 0 ? Math.round((sifCount / totalAnalyzed) * 1000) / 10 : 0;

    const sifDistribution: SifDistributionMetrics = {
      sif_potential_count: sifCount,
      non_sif_potential_count: nonSifCount,
      needs_review_count: needsReviewCount,
      total_analyzed: totalAnalyzed,
      sif_rate_pct: sifRatePct,
      policy_applied: policy,
      human_confirmed_count: humanConfirmedCount,
      human_corrected_count: humanCorrectedCount,
      pending_review_count: currentReports.filter((r) => r.review_status !== 'Completed').length,
    };

    // 2. Risk Distribution
    const riskDistribution: RiskDistributionMetrics = {
      LOW: 0,
      MEDIUM: 0,
      HIGH: 0,
      CRITICAL: 0,
      NEEDS_REVIEW: 0,
      total_assessed: 0,
      high_critical_count: 0,
      high_critical_pct: 0,
      average_score: 0,
    };

    let totalRiskScore = 0;
    for (const r of currentReports) {
      const assessment = dataStore.getLatestRiskAssessment(r.id);
      const prio = assessment?.priority || r.latest_analysis?.priority || 'NEEDS_REVIEW';
      const score = assessment?.score || 0;

      if (riskDistribution[prio] !== undefined) {
        riskDistribution[prio]++;
      }
      if (assessment) {
        totalRiskScore += score;
        riskDistribution.total_assessed++;
      }
    }

    riskDistribution.high_critical_count = riskDistribution.HIGH + riskDistribution.CRITICAL;
    riskDistribution.high_critical_pct =
      currentReports.length > 0
        ? Math.round((riskDistribution.high_critical_count / currentReports.length) * 1000) / 10
        : 0;
    riskDistribution.average_score =
      riskDistribution.total_assessed > 0
        ? Math.round(totalRiskScore / riskDistribution.total_assessed)
        : 0;

    // Previous high/critical for comparison
    let prevHighCritical = 0;
    for (const r of previousReports) {
      const assessment = dataStore.getLatestRiskAssessment(r.id);
      const prio = assessment?.priority || r.latest_analysis?.priority;
      if (prio === 'HIGH' || prio === 'CRITICAL') prevHighCritical++;
    }

    // 3. Precursors & Hazards
    const precursorMap: Map<string, { count: number; sifCount: number; hazard: string }> = new Map();
    for (const r of currentReports) {
      const text = `${r.description || ''} ${r.actual_outcome || ''}`.toLowerCase();
      let category = 'Other Operational Observations';
      let hazard = 'GENERAL_OPERATIONAL';

      if (text.includes('pressure') || text.includes('whip check') || text.includes('hydrostatic') || text.includes('psi')) {
        category = 'Pressurized Line Containment & Whip-Check';
        hazard = 'PRESSURE_STORED_ENERGY';
      } else if (text.includes('height') || text.includes('scaffold') || text.includes('fall') || text.includes('lanyard')) {
        category = 'Working at Height & Fall Arrest';
        hazard = 'GRAVITATIONAL_ENERGY';
      } else if (text.includes('loto') || text.includes('isolation') || text.includes('energized') || text.includes('breaker')) {
        category = 'Hazardous Energy & LOTO Isolation';
        hazard = 'ELECTRICAL_MECHANICAL';
      } else if (text.includes('crane') || text.includes('suspended load') || text.includes('rigging') || text.includes('sling')) {
        category = 'Line of Fire & Suspended Rigging Loads';
        hazard = 'MECHANICAL_LIFTING';
      } else if (text.includes('confined space') || text.includes('gas') || text.includes('h2s') || text.includes('oxygen')) {
        category = 'Confined Space & Gas Clearances';
        hazard = 'TOXIC_ATMOSPHERIC';
      }

      const isSif =
        r.latest_analysis?.classification === 'SIF_POTENTIAL' ||
        r.latest_analysis?.sif_potential === true;

      const curr = precursorMap.get(category) || { count: 0, sifCount: 0, hazard };
      curr.count++;
      if (isSif) curr.sifCount++;
      precursorMap.set(category, curr);
    }

    const topPrecursors: PrecursorMetricItem[] = Array.from(precursorMap.entries())
      .map(([category, val]) => ({
        category,
        count: val.count,
        share_pct: currentReports.length > 0 ? Math.round((val.count / currentReports.length) * 1000) / 10 : 0,
        sif_associated_count: val.sifCount,
        primary_hazard: val.hazard,
      }))
      .sort((a, b) => b.count - a.count);

    // 4. Barrier Failures (explicit preservation of UNKNOWN)
    const barrierMap: Map<string, { count: number; state: BarrierMetricItem['observed_state']; sites: Set<string> }> = new Map();
    for (const r of currentReports) {
      const text = `${r.description || ''} ${r.actual_outcome || ''}`.toLowerCase();
      const siteName = r.site?.name || r.site_id;

      if (text.includes('whip check') || text.includes('restraint')) {
        const key = 'Secondary Whip Check Cable Restraint';
        const item = barrierMap.get(key) || { count: 0, state: 'BYPASSED', sites: new Set() };
        item.count++;
        item.sites.add(siteName);
        barrierMap.set(key, item);
      }
      if (text.includes('barricade') || text.includes('line of fire') || text.includes('perimeter')) {
        const key = 'Exclusion Barricade Zone Perimeter';
        const item = barrierMap.get(key) || { count: 0, state: 'FAILED', sites: new Set() };
        item.count++;
        item.sites.add(siteName);
        barrierMap.set(key, item);
      }
      if (text.includes('lanyard') || text.includes('harness') || text.includes('unclipped')) {
        const key = '100% Dual-Lanyard Fall Arrest Tethering';
        const item = barrierMap.get(key) || { count: 0, state: 'FAILED', sites: new Set() };
        item.count++;
        item.sites.add(siteName);
        barrierMap.set(key, item);
      }
      if (text.includes('loto') || text.includes('lockout') || text.includes('isolation')) {
        const key = 'Positive Energy Lockout/Tagout (LOTO)';
        const item = barrierMap.get(key) || { count: 0, state: 'INADEQUATE', sites: new Set() };
        item.count++;
        item.sites.add(siteName);
        barrierMap.set(key, item);
      }
      if (text.includes('gas') || text.includes('monitor') || text.includes('test')) {
        const key = 'Continuous Multi-Gas Air Clearance Testing';
        const item = barrierMap.get(key) || { count: 0, state: 'NOT_VERIFIED', sites: new Set() };
        item.count++;
        item.sites.add(siteName);
        barrierMap.set(key, item);
      }

      // Preserving reports where barrier status is explicitly UNKNOWN
      if (r.latest_analysis?.confidence_band === 'LOW' || !r.latest_analysis?.hazards?.length) {
        const key = 'Unverified Barrier Integrity Context';
        const item = barrierMap.get(key) || { count: 0, state: 'UNKNOWN', sites: new Set() };
        item.count++;
        item.sites.add(siteName);
        barrierMap.set(key, item);
      }
    }

    const barrierFailures: BarrierMetricItem[] = Array.from(barrierMap.entries()).map(
      ([cat, val]) => ({
        barrier_category: cat,
        observed_state: val.state,
        count: val.count,
        share_pct: currentReports.length > 0 ? Math.round((val.count / currentReports.length) * 1000) / 10 : 0,
        affected_sites: Array.from(val.sites),
      })
    );

    // 5. IOGP Life-Saving Rules concordance
    const iogpRulesMap: Map<string, { count: number; sifCount: number; activities: Set<string> }> = new Map();
    const rulesList = [
      { name: 'Line of Fire', keywords: ['line of fire', 'pressure', 'whip check', 'suspended', 'rigging'] },
      { name: 'Working at Height', keywords: ['height', 'scaffold', 'fall', 'harness', 'lanyard'] },
      { name: 'Energy Isolation', keywords: ['isolation', 'loto', 'energized', 'breaker', 'lockout'] },
      { name: 'Safe Mechanical Lifting', keywords: ['crane', 'sling', 'lift', 'hoist', 'rigging'] },
      { name: 'Confined Space Entry', keywords: ['confined space', 'mud tank entry', 'vessel', 'gas test'] },
      { name: 'Bypassing Safety Controls', keywords: ['bypass', 'override', 'defeated', 'unauthorized'] },
    ];

    for (const r of currentReports) {
      const text = `${r.description || ''} ${r.actual_outcome || ''}`.toLowerCase();
      const isSif =
        r.latest_analysis?.classification === 'SIF_POTENTIAL' ||
        r.latest_analysis?.sif_potential === true;
      const actName = r.activity?.name || 'General Operations';

      for (const rule of rulesList) {
        if (rule.keywords.some((kw) => text.includes(kw))) {
          const item = iogpRulesMap.get(rule.name) || { count: 0, sifCount: 0, activities: new Set() };
          item.count++;
          if (isSif) item.sifCount++;
          item.activities.add(actName);
          iogpRulesMap.set(rule.name, item);
        }
      }
    }

    const iogpRules: IogpRuleMetricItem[] = Array.from(iogpRulesMap.entries())
      .map(([name, val]) => ({
        rule_name: name,
        report_count: val.count,
        share_pct: currentReports.length > 0 ? Math.round((val.count / currentReports.length) * 1000) / 10 : 0,
        sif_count: val.sifCount,
        associated_activities: Array.from(val.activities),
      }))
      .sort((a, b) => b.report_count - a.report_count);

    // 6. Site Summaries
    const siteAggregations = riskAggregationService.calculateSiteAggregations(
      SITES,
      currentReports,
      (id) => dataStore.getLatestRiskAssessment(id),
      {
        organization_id: orgId,
        min_sample: 5,
      }
    );

    const siteSummaries: SiteAnalyticsItem[] = siteAggregations.map((agg) => {
      const siteActions = actionStore.getActions({ organization_id: orgId, site_id: agg.site_id }).data || [];
      const openActions = siteActions.filter((a) => !['CLOSED', 'CANCELLED'].includes(a.status)).length;
      const overdueActions = siteActions.filter((a) => a.is_overdue).length;
      const siteReviews = reviewStore.getQueue(
        { organization_id: orgId, site_id: agg.site_id },
        (id) => dataStore.getReportById(id) || undefined
      ).reviews;

      return {
        site_id: agg.site_id,
        site_code: agg.site_code,
        site_name: agg.site_name,
        site_type: agg.site_type,
        report_count: agg.total_reports,
        sif_count: agg.sif_reports,
        sif_rate_pct: agg.sif_precursor_density_pct,
        precursor_density: agg.sif_precursor_density,
        dominant_priority: agg.dominant_priority,
        recurring_patterns_count: patternStore.getPatterns(orgId, { site_id: agg.site_id }).total,
        open_actions_count: openActions,
        overdue_actions_count: overdueActions,
        pending_reviews_count: siteReviews.filter((r) => r.status !== 'COMPLETED').length,
        sample_sufficiency: agg.sample_sufficiency,
      };
    });

    // 7. Activity Summaries
    const activityAggregations = riskAggregationService.calculateActivityAggregations(
      ACTIVITIES,
      currentReports,
      (id) => dataStore.getLatestRiskAssessment(id),
      {
        organization_id: orgId,
        min_sample: 5,
      }
    );

    const activitySummaries: ActivityAnalyticsItem[] = activityAggregations.map((agg) => ({
      activity_id: agg.activity_id,
      activity_code: agg.activity_code,
      activity_name: agg.activity_name,
      category: agg.category,
      report_count: agg.total_reports,
      sif_count: agg.sif_reports,
      sif_rate_pct: agg.sif_precursor_density_pct,
      dominant_priority: agg.dominant_priority,
      top_precursors: ['Line of Fire', 'Working at Height'],
      sample_sufficiency: agg.sample_sufficiency,
    }));

    // 8. Recurring Patterns (Phase 8)
    const patternsRes = patternStore.getPatterns(orgId);
    const patternSummaryKpis = patternStore.getPatternSummary(orgId);
    const patternSummary: PatternAnalyticsMetrics = {
      total_patterns: patternSummaryKpis.total_patterns,
      active_emerging: patternSummaryKpis.emerging_patterns,
      active_persistent: patternSummaryKpis.persistent_patterns,
      inactive_archived: patternSummaryKpis.archived_patterns,
      top_patterns: patternsRes.patterns.slice(0, 5).map((p) => ({
        id: p.id,
        title: p.title,
        pattern_type: p.pattern_type,
        status: p.status,
        support_count: p.support_count,
        pattern_strength: p.pattern_strength,
        affected_sites_count: p.distributions?.sites?.length || p.evidence_summary?.distinct_sites || (p.related_sites ? p.related_sites.length + 1 : 1),
        first_seen_at: p.first_seen_at,
        last_seen_at: p.last_seen_at,
      })),
    };

    // 9. Review Queue (Phase 9)
    const reviewKpis = reviewStore.getSummaryKPIs(orgId);
    const reviewSummary: ReviewAnalyticsMetrics = {
      total_in_queue: reviewKpis.total_in_queue,
      pending_unassigned: reviewKpis.pending,
      assigned_in_progress: reviewKpis.in_review + reviewKpis.assigned,
      completed_total: reviewKpis.completed,
      confirmed_ai: reviewKpis.confirmed,
      corrected_ai: reviewKpis.corrected,
      rejected_ai: reviewKpis.rejected,
      stale_reviews: reviewKpis.stale,
      average_review_age_hours: reviewKpis.average_review_age_hours,
      review_backlog_days: Math.round((reviewKpis.average_review_age_hours / 24) * 10) / 10,
    };

    // 10. CAPA (Phase 10)
    const actionKpis = actionStore.getSummary(orgId);
    const allActions = actionStore.getActions({ organization_id: orgId, page_size: 100 }).data || [];

    const aging = {
      days_0_to_7: 0,
      days_8_to_30: 0,
      days_31_to_60: 0,
      days_over_60: 0,
    };

    const nowMs = Date.now();
    for (const a of allActions) {
      if (!['CLOSED', 'CANCELLED'].includes(a.status)) {
        const createdMs = new Date(a.created_at).getTime();
        const ageDays = Math.max(0, Math.floor((nowMs - createdMs) / 86400000));
        if (ageDays <= 7) aging.days_0_to_7++;
        else if (ageDays <= 30) aging.days_8_to_30++;
        else if (ageDays <= 60) aging.days_31_to_60++;
        else aging.days_over_60++;
      }
    }

    const eligibleActions = actionKpis.total_actions - allActions.filter((a) => a.status === 'CANCELLED').length;
    const resolvedActions = actionKpis.closed_actions + actionKpis.verified_actions;
    const completionRatePct = eligibleActions > 0 ? Math.round((resolvedActions / eligibleActions) * 1000) / 10 : 0;

    const capaSummary: CapaAnalyticsMetrics = {
      total_actions: actionKpis.total_actions,
      open_actions: actionKpis.open_actions,
      assigned_actions: actionKpis.assigned_actions,
      in_progress_actions: actionKpis.in_progress_actions,
      verification_required_actions: actionKpis.verification_required_actions,
      verified_actions: actionKpis.verified_actions,
      closed_actions: actionKpis.closed_actions,
      overdue_actions: actionKpis.overdue_actions,
      reopened_actions: actionKpis.reopened_actions,
      completion_rate_pct: completionRatePct,
      aging_distribution: aging,
    };

    // 11. Alerts (Phase 11)
    const alertMetrics = alertStore.getMetrics(orgId);
    const allAlertsList = alertStore.listAlerts({ organization_id: orgId, page_size: 200 }).data || [];
    const bySeverity = {
      CRITICAL: allAlertsList.filter((a) => a.severity === 'CRITICAL').length,
      HIGH: allAlertsList.filter((a) => a.severity === 'HIGH').length,
      WARNING: allAlertsList.filter((a) => a.severity === 'WARNING').length,
      NOTICE: allAlertsList.filter((a) => a.severity === 'NOTICE').length,
      INFO: allAlertsList.filter((a) => a.severity === 'INFO').length,
    };
    const byCategory: Record<string, number> = {};
    for (const a of allAlertsList) {
      byCategory[a.category] = (byCategory[a.category] || 0) + 1;
    }

    const alertSummary: AlertAnalyticsMetrics = {
      total_alerts: allAlertsList.length,
      active_unread: alertMetrics.unread_count,
      acknowledged: alertMetrics.acknowledged_count,
      resolved: alertMetrics.resolved_count,
      escalated: allAlertsList.filter((a) => (a.escalation_level || 0) > 1).length,
      dismissed: allAlertsList.filter((a) => a.status === 'DISMISSED').length,
      by_severity: bySeverity,
      by_category: byCategory,
    };

    // 12. Time-series trend generation
    const dateBucketMap: Map<string, { total: number; sif: number; nonSif: number; highCrit: number }> = new Map();

    // Sort reports chronologically for timeline
    const chronologicalReports = [...currentReports].sort(
      (a, b) => new Date(a.report_datetime || a.created_at).getTime() - new Date(b.report_datetime || b.created_at).getTime()
    );

    for (const r of chronologicalReports) {
      const d = (r.report_datetime || r.created_at).substring(0, 10);
      const entry = dateBucketMap.get(d) || { total: 0, sif: 0, nonSif: 0, highCrit: 0 };
      entry.total++;

      const isSif = r.latest_analysis?.classification === 'SIF_POTENTIAL' || r.latest_analysis?.sif_potential === true;
      if (isSif) entry.sif++;
      else entry.nonSif++;

      const prio = r.latest_risk_assessment?.priority || r.latest_analysis?.priority;
      if (prio === 'HIGH' || prio === 'CRITICAL') entry.highCrit++;

      dateBucketMap.set(d, entry);
    }

    const trendSeries: TimeSeriesPoint[] = Array.from(dateBucketMap.entries()).map(([date, val]) => ({
      date,
      timestamp: new Date(date).toISOString(),
      total_reports: val.total,
      sif_potential: val.sif,
      non_sif_potential: val.nonSif,
      high_critical_risk: val.highCrit,
    }));

    // 13. Heatmap (Site vs Precursor Category)
    const heatmapCells: HeatmapCell[] = [];
    let maxHeatVal = 1;

    for (const site of SITES) {
      for (const prec of topPrecursors.slice(0, 5)) {
        let matchCount = 0;
        for (const r of currentReports) {
          if (r.site_id === site.id || r.site?.code === site.code) {
            const text = `${r.description} ${r.actual_outcome || ''}`.toLowerCase();
            if (prec.category.includes('Pressurized') && (text.includes('pressure') || text.includes('whip check'))) matchCount++;
            else if (prec.category.includes('Height') && (text.includes('height') || text.includes('fall') || text.includes('scaffold'))) matchCount++;
            else if (prec.category.includes('Energy') && (text.includes('loto') || text.includes('isolation') || text.includes('energized'))) matchCount++;
            else if (prec.category.includes('Line of Fire') && (text.includes('crane') || text.includes('suspended') || text.includes('rigging'))) matchCount++;
            else if (prec.category.includes('Confined') && (text.includes('confined') || text.includes('gas') || text.includes('oxygen'))) matchCount++;
          }
        }
        if (matchCount > maxHeatVal) maxHeatVal = matchCount;
        heatmapCells.push({
          x_label: site.name.replace(/\[.*\]/, '').trim(),
          y_label: prec.category,
          value: matchCount,
          intensity: 0, // calculated below
        });
      }
    }
    for (const cell of heatmapCells) {
      cell.intensity = maxHeatVal > 0 ? Math.round((cell.value / maxHeatVal) * 100) / 100 : 0;
    }

    // 14. Data Quality
    const analyzedCount = currentReports.filter((r) => r.latest_analysis).length;
    const completenessPct = currentReports.length > 0 ? Math.round((analyzedCount / currentReports.length) * 1000) / 10 : 100;

    const dataQuality: DataQualitySummary = {
      total_reports: currentReports.length,
      analyzed_reports: analyzedCount,
      pending_analysis_reports: currentReports.length - analyzedCount,
      human_reviewed_reports: currentReports.filter((r) => r.review_status === 'Completed').length,
      uncertain_barrier_observations: barrierFailures.filter((b) => b.observed_state === 'UNKNOWN').length,
      uncertain_iogp_mappings: currentReports.filter((r) => !r.latest_analysis?.hazards?.length).length,
      data_completeness_pct: completenessPct,
      data_status: 'SYNTHETIC_DEMO',
      disclaimer: 'SUCHAK Demo Protocol Data: All metrics are computed deterministically over synthetic demonstration records. Not live OIL enterprise telemetry.',
    };

    // 15. Executive KPI Strip with safe comparisons
    const kpiStrip: KPICardData[] = [
      {
        metric_id: 'TOTAL_REPORTS',
        label: 'Total Reports',
        value: currentReports.length,
        formatted_value: currentReports.length.toLocaleString(),
        unit: 'reports',
        comparison: this.calculateComparison(currentReports.length, previousReports.length),
        definition: METRIC_DEFINITIONS.TOTAL_REPORTS.definition,
        authoritative_source: METRIC_DEFINITIONS.TOTAL_REPORTS.authoritative_source,
        drill_down_path: '/reports',
        drill_down_label: 'View Filtered Reports',
      },
      {
        metric_id: 'SIF_POTENTIAL',
        label: 'SIF Potential',
        value: sifCount,
        formatted_value: sifCount.toLocaleString(),
        unit: 'signals',
        comparison: this.calculateComparison(sifCount, prevSifCount),
        definition: METRIC_DEFINITIONS.SIF_POTENTIAL.definition,
        authoritative_source: METRIC_DEFINITIONS.SIF_POTENTIAL.authoritative_source,
        drill_down_path: '/reports?sif_potential=true',
        drill_down_label: 'Inspect SIF Reports',
      },
      {
        metric_id: 'HIGH_CRITICAL_PRIORITY',
        label: 'High/Critical Risk',
        value: riskDistribution.high_critical_count,
        formatted_value: riskDistribution.high_critical_count.toLocaleString(),
        unit: 'reports',
        comparison: this.calculateComparison(riskDistribution.high_critical_count, prevHighCritical),
        definition: METRIC_DEFINITIONS.HIGH_CRITICAL_PRIORITY.definition,
        authoritative_source: METRIC_DEFINITIONS.HIGH_CRITICAL_PRIORITY.authoritative_source,
        drill_down_path: '/reports?priority=HIGH',
        drill_down_label: 'View High Priority',
      },
      {
        metric_id: 'RECURRING_PATTERNS',
        label: 'Recurring Patterns',
        value: patternSummary.active_emerging + patternSummary.active_persistent,
        formatted_value: (patternSummary.active_emerging + patternSummary.active_persistent).toLocaleString(),
        unit: 'active clusters',
        definition: METRIC_DEFINITIONS.RECURRING_PATTERNS.definition,
        authoritative_source: METRIC_DEFINITIONS.RECURRING_PATTERNS.authoritative_source,
        drill_down_path: '/patterns',
        drill_down_label: 'Open Pattern Center',
      },
      {
        metric_id: 'OPEN_ACTIONS',
        label: 'Open CAPA Actions',
        value: capaSummary.open_actions + capaSummary.in_progress_actions + capaSummary.assigned_actions,
        formatted_value: (capaSummary.open_actions + capaSummary.in_progress_actions + capaSummary.assigned_actions).toLocaleString(),
        unit: 'actions',
        definition: METRIC_DEFINITIONS.OPEN_ACTIONS.definition,
        authoritative_source: METRIC_DEFINITIONS.OPEN_ACTIONS.authoritative_source,
        drill_down_path: '/actions',
        drill_down_label: 'Go to Action Center',
      },
      {
        metric_id: 'OVERDUE_ACTIONS',
        label: 'Overdue Actions',
        value: capaSummary.overdue_actions,
        formatted_value: capaSummary.overdue_actions.toLocaleString(),
        unit: 'overdue',
        definition: METRIC_DEFINITIONS.OVERDUE_ACTIONS.definition,
        authoritative_source: METRIC_DEFINITIONS.OVERDUE_ACTIONS.authoritative_source,
        drill_down_path: '/actions?overdue_only=true',
        drill_down_label: 'View Overdue Actions',
      },
      {
        metric_id: 'PENDING_REVIEWS',
        label: 'Pending Reviews',
        value: reviewSummary.pending_unassigned + reviewSummary.assigned_in_progress,
        formatted_value: (reviewSummary.pending_unassigned + reviewSummary.assigned_in_progress).toLocaleString(),
        unit: 'in queue',
        definition: METRIC_DEFINITIONS.PENDING_REVIEWS.definition,
        authoritative_source: METRIC_DEFINITIONS.PENDING_REVIEWS.authoritative_source,
        drill_down_path: '/review',
        drill_down_label: 'Process Review Queue',
      },
      {
        metric_id: 'ACTIVE_ALERTS',
        label: 'Active Alerts',
        value: alertSummary.active_unread + alertSummary.acknowledged,
        formatted_value: (alertSummary.active_unread + alertSummary.acknowledged).toLocaleString(),
        unit: 'alerts',
        definition: METRIC_DEFINITIONS.ACTIVE_ALERTS.definition,
        authoritative_source: METRIC_DEFINITIONS.ACTIVE_ALERTS.authoritative_source,
        drill_down_path: '/alerts',
        drill_down_label: 'Review Alerts',
      },
    ];

    // 16. Deterministic executive narrative summary
    const deterministicSummary =
      `During the selected ${windows.preset} reporting window, ${currentReports.length} observation reports ` +
      `were evaluated across ${SITES.length} operational assets. ${sifCount} reports (${sifRatePct}%) were classified as ` +
      `SIF Potential under active review policy (${policy}). The primary precursor cluster observed is ` +
      `'${topPrecursors[0]?.category || 'General Operations'}' with ${topPrecursors[0]?.count || 0} associated reports. ` +
      `Across corrective workflows, ${capaSummary.open_actions} CAPA actions are open (${capaSummary.overdue_actions} overdue), ` +
      `and ${reviewSummary.total_in_queue} reports reside in the human review queue.`;

    const result: AnalyticsOverviewResponse = {
      schema_version: ANALYTICS_SCHEMA_VERSION,
      metric_version: METRIC_DEFINITION_VERSION,
      generated_at: new Date().toISOString(),
      period: {
        start: windows.currentStart ? windows.currentStart.toISOString() : 'Earliest Recorded',
        end: windows.currentEnd.toISOString(),
        preset: windows.preset,
        previous_start: windows.previousStart ? windows.previousStart.toISOString() : undefined,
        previous_end: windows.previousEnd ? windows.previousEnd.toISOString() : undefined,
      },
      filters: options,
      kpi_strip: kpiStrip,
      sif_distribution: sifDistribution,
      risk_distribution: riskDistribution,
      top_precursors: topPrecursors,
      barrier_failures: barrierFailures,
      iogp_rules: iogpRules,
      site_summaries: siteSummaries,
      activity_summaries: activitySummaries,
      pattern_summary: patternSummary,
      review_summary: reviewSummary,
      capa_summary: capaSummary,
      alert_summary: alertSummary,
      trend_series: trendSeries,
      heatmap: {
        x_axis: 'Site / Asset',
        y_axis: 'Precursor Category',
        cells: heatmapCells,
      },
      data_quality: dataQuality,
      deterministic_summary: deterministicSummary,
      methodology_statement:
        'Count / Rate / Distribution / Trend ≠ Causation ≠ Prediction ≠ Autonomous Decision. SIF Classification ≠ Risk Priority ≠ Pattern Strength ≠ Alert Severity. Evaluated deterministically under SUCHAK Analytics v1 protocol.',
    };

    // Store in cache
    this.cache.set(cacheKey, { data: result, expiry: Date.now() + this.cacheTtlMs });

    return result;
  }

  /**
   * Generates a formal Management Summary Report
   */
  public async generateManagementSummary(
    options: AnalyticsFilterOptions = {}
  ): Promise<ManagementReportSummary> {
    const overview = await this.getOverview(options);

    return {
      report_id: `MGT-REP-${Date.now().toString(36).toUpperCase()}`,
      organization_id: options.organization_id || 'oil-india-demo',
      generated_at: new Date().toISOString(),
      reporting_period: {
        start_date: overview.period.start,
        end_date: overview.period.end,
        preset: overview.period.preset,
      },
      headline_metrics: {
        total_reports: overview.kpi_strip.find((k) => k.metric_id === 'TOTAL_REPORTS')?.value || 0,
        sif_potential_count: overview.sif_distribution.sif_potential_count,
        high_critical_risk_count: overview.risk_distribution.high_critical_count,
        recurring_patterns_count: overview.pattern_summary.total_patterns,
        open_actions_count: overview.capa_summary.open_actions,
        overdue_actions_count: overview.capa_summary.overdue_actions,
        pending_reviews_count: overview.review_summary.total_in_queue,
        active_alerts_count: overview.alert_summary.total_alerts,
      },
      sif_distribution: overview.sif_distribution,
      top_precursor_clusters: overview.top_precursors.map((p) => ({
        name: p.category,
        count: p.count,
        share_pct: p.share_pct,
      })),
      barrier_defense_health: overview.barrier_failures.map((b) => ({
        barrier: b.barrier_category,
        failure_count: b.count,
        state: b.observed_state,
      })),
      capa_status: {
        open: overview.capa_summary.open_actions,
        overdue: overview.capa_summary.overdue_actions,
        completed: overview.capa_summary.closed_actions + overview.capa_summary.verified_actions,
        completion_rate_pct: overview.capa_summary.completion_rate_pct,
      },
      data_quality: overview.data_quality,
      disclaimer: overview.methodology_statement,
    };
  }

  /**
   * Exports analytics tabular dataset as CSV string
   */
  public async exportToCsv(
    datasetType: 'reports' | 'sif' | 'sites' | 'precursors' | 'capa' | 'overview',
    options: AnalyticsFilterOptions = {}
  ): Promise<{ filename: string; csv: string }> {
    const overview = await this.getOverview(options);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    let csv = '';
    let filename = `suchak_${datasetType}_analytics_${timestamp}.csv`;

    if (datasetType === 'sites') {
      csv = 'Site Code,Site Name,Site Type,Total Reports,SIF Reports,SIF Rate %,Precursor Density,Dominant Priority,Open Actions,Overdue Actions,Sample Status\n';
      for (const s of overview.site_summaries) {
        csv += `"${s.site_code}","${s.site_name}","${s.site_type}",${s.report_count},${s.sif_count},${s.sif_rate_pct}%,${s.precursor_density},"${s.dominant_priority}",${s.open_actions_count},${s.overdue_actions_count},"${s.sample_sufficiency}"\n`;
      }
    } else if (datasetType === 'precursors') {
      csv = 'Precursor Category,Observations Count,Share %,SIF Associated Count,Primary Hazard Context\n';
      for (const p of overview.top_precursors) {
        csv += `"${p.category}",${p.count},${p.share_pct}%,${p.sif_associated_count},"${p.primary_hazard}"\n`;
      }
    } else if (datasetType === 'sif') {
      csv = 'Metric,Count,Share %,Authoritative Source,Policy Applied\n';
      csv += `"SIF Potential",${overview.sif_distribution.sif_potential_count},${overview.sif_distribution.sif_rate_pct}%,"Phase 4/9 Store","${overview.sif_distribution.policy_applied}"\n`;
      csv += `"Non-SIF Potential",${overview.sif_distribution.non_sif_potential_count},${100 - overview.sif_distribution.sif_rate_pct}%,"Phase 4/9 Store","${overview.sif_distribution.policy_applied}"\n`;
      csv += `"Needs Review",${overview.sif_distribution.needs_review_count},--,"Phase 9 Queue","${overview.sif_distribution.policy_applied}"\n`;
    } else {
      // Overview summary KPIs
      csv = 'Metric ID,Display Name,Value,Unit,Comparison Label,Authoritative Source\n';
      for (const k of overview.kpi_strip) {
        csv += `"${k.metric_id}","${k.label}",${k.value},"${k.unit || ''}","${k.comparison?.label || 'N/A'}","${k.authoritative_source}"\n`;
      }
    }

    return { filename, csv };
  }
}

export const analyticsService = new AnalyticsService();
