/**
 * SUCHAK - Enterprise HSE Safety Intelligence & Early-Warning Platform
 * Phase 13: Authoritative Benchmark Datasets & Golden Test Cases
 */

import { EvaluationDataset } from './modelGovernanceTypes.ts';

export const BENCHMARK_DATASETS: EvaluationDataset[] = [
  {
    dataset_id: 'ds-gold-upstream-v1',
    dataset_version: '1.0.0',
    name: 'Upstream O&G Golden SIF Benchmark',
    purpose: 'Curated golden benchmark for evaluating SIF detection, Line-of-Fire precursors, and IOGP Life-Saving Rules concordance.',
    task: 'MULTI_TASK',
    description: '14 authoritative high-consequence drilling, pressure testing, and confined space observation records curated by Senior HSE Officers.',
    source: 'Enterprise HSE Incident Management System & Field Review Queue',
    provenance: 'HUMAN_CURATED',
    dataset_type: 'BENCHMARK',
    record_count: 14,
    created_at: '2026-06-15T08:00:00Z',
    approved_by: 'Dr. Alok Baruah (Chief Safety Officer)',
    status: 'ACTIVE',
    class_distribution: {
      sif_potential: 8,
      non_sif_potential: 4,
      needs_review: 2,
    },
    cases: [
      {
        case_id: 'CASE-GOLD-001',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'During 10,000 psi hydrostatic pressure testing of choke manifold, pressure line whip check cable was found unfastened and swinging loose while line held 7,500 psi. Personnel were standing within 3 meters in the line of fire.',
        actual_outcome: 'Near-miss with zero injuries. Test halted immediately by safety observer.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['High-pressure line testing with compromised restraint', 'Personnel inside line-of-fire zone'],
        expected_hazards: ['PRESSURE', 'LINE_OF_FIRE'],
        expected_exposure: ['Pressure manifold perimeter', 'Drill floor high-pressure zone'],
        expected_barriers: [
          { barrier_name: 'Whip Check Restraint Cable', status: 'BYPASSED' },
          { barrier_name: 'Physical Exclusion Barricade', status: 'FAILED' },
        ],
        expected_iogp_mapping: ['Line of Fire', 'Energy Isolation'],
        expected_priority: 'CRITICAL',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-alok-01',
        annotator_role: 'Chief Safety Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['high-pressure', 'line-of-fire', 'drilling', 'critical'],
      },
      {
        case_id: 'CASE-GOLD-002',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Derrickman spotted standing on monkey board 90 feet above drill floor without secondary harness tether latched. Lanyard was draped over guardrail but carabiner was unlocked while latching drill pipe stands.',
        actual_outcome: 'Observed during routine walkaround. Derrickman recalled and tether secured.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Elevated work without verified primary fall arrest tethering'],
        expected_hazards: ['GRAVITY'],
        expected_exposure: ['Derrick mast elevation > 25m'],
        expected_barriers: [
          { barrier_name: 'Self-Retracting Fall Arrest Lifeline', status: 'BYPASSED' },
        ],
        expected_iogp_mapping: ['Work at Height'],
        expected_priority: 'HIGH',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-priyanka-02',
        annotator_role: 'HSE Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['height', 'gravity', 'derrick', 'critical'],
      },
      {
        case_id: 'CASE-GOLD-003',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Two contract technicians entered crude storage tank T-104 for desludging without continuous multi-gas monitor calibrated and without positive forced air ventilation duct running.',
        actual_outcome: 'Atmosphere test at entry hatch showed 19.8% O2 and 12 ppm H2S. Work stopped immediately.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Confined space entry without verified atmospheric monitoring or forced ventilation'],
        expected_hazards: ['HAZARDOUS_ATMOSPHERE', 'TOXIC_GAS'],
        expected_exposure: ['Crude storage vessel interior'],
        expected_barriers: [
          { barrier_name: 'Continuous Gas Detection Barrier', status: 'FAILED' },
          { barrier_name: 'Forced Mechanical Ventilation', status: 'BYPASSED' },
        ],
        expected_iogp_mapping: ['Confined Space', 'Toxic Gas Exposure'],
        expected_priority: 'CRITICAL',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['confined-space', 'toxic-gas', 'h2s', 'critical'],
      },
      {
        case_id: 'CASE-GOLD-004',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Mobile crane operator initiated 14-ton mud pump skid lift without taglines attached. Load swung abruptly when 25-knot gust hit, coming within 40 cm of pressurized gas separator line.',
        actual_outcome: 'Near-impact with active separator process header. Load lowered to ground safely.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Suspended heavy load lifting without tagline guide controls near pressurized assets'],
        expected_hazards: ['MECHANICAL', 'PRESSURE', 'LINE_OF_FIRE'],
        expected_exposure: ['Crane operating radius and process piping corridor'],
        expected_barriers: [
          { barrier_name: 'Tagline Control Protocol', status: 'BYPASSED' },
          { barrier_name: 'Heavy Lift Radius Buffer', status: 'INADEQUATE' },
        ],
        expected_iogp_mapping: ['Lifting Operations', 'Line of Fire'],
        expected_priority: 'HIGH',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-priyanka-02',
        annotator_role: 'HSE Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['lifting', 'crane', 'dropped-object'],
      },
      {
        case_id: 'CASE-GOLD-005',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Housekeeping observation: Plastic wrapping and two empty cardboard packaging boxes left near rig workshop entrance. Walkway remained unobstructed and dry.',
        actual_outcome: 'Housekeeping noted; cleared during shift handover.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: [],
        expected_hazards: [],
        expected_exposure: [],
        expected_barriers: [],
        expected_iogp_mapping: [],
        expected_priority: 'LOW',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['housekeeping', 'low-risk'],
      },
      {
        case_id: 'CASE-GOLD-006',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Contractor safety glasses scratched on right lens. Employee requested replacement pair from warehouse tool crib prior to starting grinder cutting.',
        actual_outcome: 'New PPE issued from stores.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: [],
        expected_hazards: [],
        expected_exposure: [],
        expected_barriers: [],
        expected_iogp_mapping: [],
        expected_priority: 'LOW',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['ppe', 'low-risk'],
      },
      {
        case_id: 'CASE-GOLD-007',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Hot work permit active for welding pipe support at crude manifold. Fire watch was present with dry chemical extinguisher, but spark containment blanket had a 30cm tear, allowing occasional sparks to drift toward oily sump pit.',
        actual_outcome: 'Sparks extinguished before reaching vapor pocket. Sump covered with flame retardant tarp.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Hot work spark containment breach adjacent to hydrocarbon vapor accumulation zone'],
        expected_hazards: ['THERMAL', 'HAZARDOUS_ATMOSPHERE'],
        expected_exposure: ['Crude manifold sump area'],
        expected_barriers: [
          { barrier_name: 'Fire Retardant Containment Blanket', status: 'FAILED' },
        ],
        expected_iogp_mapping: ['Hot Work'],
        expected_priority: 'CRITICAL',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-alok-01',
        annotator_role: 'Chief Safety Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['hot-work', 'hydrocarbon', 'fire-barrier'],
      },
      {
        case_id: 'CASE-GOLD-008',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Forklift operator found driving at 15 km/h across warehouse apron without sounding horn at blind intersection. Pallet load of dry mud additives was securely shrink-wrapped.',
        actual_outcome: 'No collision. Driver briefed on speed limits and blind spot sounding protocol.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: ['Mobile equipment operation without acoustic warning at blind corners'],
        expected_hazards: ['TRAFFIC'],
        expected_exposure: ['Warehouse apron pedestrian crossing'],
        expected_barriers: [
          { barrier_name: 'Speed Limiter and Audible Horn Warning', status: 'BYPASSED' },
        ],
        expected_iogp_mapping: ['Driving'],
        expected_priority: 'MEDIUM',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-manish-04',
        annotator_role: 'Site Manager',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['mobile-plant', 'warehouse', 'traffic'],
      },
      {
        case_id: 'CASE-GOLD-009',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'During pigging receiver barrel door opening on main sales gas pipeline, operator cracked bleed vent. A strong hissing sound occurred indicating trapped line pressure at 40 bar behind pig.',
        actual_outcome: 'Door opening aborted. Valve reseated and secondary depressurization loop engaged.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Vessel opening attempt with trapped pressurized gas behind stuck pig'],
        expected_hazards: ['PRESSURE', 'LINE_OF_FIRE'],
        expected_exposure: ['Pig receiver head-on trajectory'],
        expected_barriers: [
          { barrier_name: 'Zero Energy Pressure Verification Barrier', status: 'FAILED' },
        ],
        expected_iogp_mapping: ['Energy Isolation', 'Line of Fire'],
        expected_priority: 'CRITICAL',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-alok-01',
        annotator_role: 'Chief Safety Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['pigging', 'pipeline', 'stored-energy', 'critical'],
      },
      {
        case_id: 'CASE-GOLD-010',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Report describes a field technician who slipped on muddy grass verge outside perimeter fence. Slight ankle roll with zero swelling; walked back to vehicle unassisted.',
        actual_outcome: 'First aid kit applied cold pack as precaution. Full mobility.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: [],
        expected_hazards: [],
        expected_exposure: [],
        expected_barriers: [],
        expected_iogp_mapping: [],
        expected_priority: 'LOW',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['slip-trip', 'low-risk'],
      },
      {
        case_id: 'CASE-GOLD-011',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Subcontractor crew was excavating a 2.4 meter deep trench for instrument cable laying without trench box shoring or stepped benching. Soil was loose alluvial sand with heavy excavator idling 1 meter from trench lip.',
        actual_outcome: 'HSE officer halted dig immediately. Workers evacuated from unshored trench.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Unshored deep excavation exceeding 2m in loose soil with surcharge load on rim'],
        expected_hazards: ['CAVE_IN', 'GRAVITY'],
        expected_exposure: ['Excavation floor trench perimeter'],
        expected_barriers: [
          { barrier_name: 'Trench Shoring Box & Benching', status: 'BYPASSED' },
        ],
        expected_iogp_mapping: ['Line of Fire', 'Work at Height'],
        expected_priority: 'CRITICAL',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-priyanka-02',
        annotator_role: 'HSE Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['excavation', 'trench', 'cave-in', 'critical'],
      },
      {
        case_id: 'CASE-GOLD-012',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Electrical technician tested 440V motor control cabinet without verified lockout tagout padlocks affixed to main breaker. Assistant was standing nearby holding insulated probe.',
        actual_outcome: 'Intervention by electrical lead. Breaker de-energized, LOTO lock applied.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Work on 440V high-power distribution panel without verified physical LOTO lock'],
        expected_hazards: ['ELECTRICAL', 'ARC_FLASH'],
        expected_exposure: ['Motor control center panel board'],
        expected_barriers: [
          { barrier_name: 'Physical Padlock Lockout Tagout (LOTO)', status: 'BYPASSED' },
        ],
        expected_iogp_mapping: ['Energy Isolation'],
        expected_priority: 'CRITICAL',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-alok-01',
        annotator_role: 'Chief Safety Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['electrical', 'loto', 'arc-flash', 'critical'],
      },
      {
        case_id: 'CASE-GOLD-013',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Worker smelled faint sweet gas odor near flange at manifold header #3. Portable gas sensor detected intermittent 5% LEL hydrocarbons. Atmospheric test was inconclusive due to high cross-wind gusts.',
        actual_outcome: 'Flange retorqued. Perimeter cordoned off pending repeat sniffer test.',
        expected_sif: 'NEEDS_REVIEW',
        expected_precursors: ['Intermittent hydrocarbon leak detection under fluctuating meteorological dispersion'],
        expected_hazards: ['HAZARDOUS_ATMOSPHERE'],
        expected_exposure: ['Manifold header perimeter'],
        expected_barriers: [
          { barrier_name: 'Flange Gasket Seal', status: 'UNKNOWN' },
        ],
        expected_iogp_mapping: ['Line of Fire'],
        expected_priority: 'MEDIUM',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'ANNOTATION_CONFLICT',
        agreement_notes: 'Annotators split: Reviewer marked NEEDS_REVIEW due to gust dispersion uncertainty; Field lead argued SIF_POTENTIAL given proximity to generator ignition source.',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['ambiguous', 'gas-leak', 'annotation-conflict'],
      },
      {
        case_id: 'CASE-GOLD-014',
        dataset_id: 'ds-gold-upstream-v1',
        input_text: 'Valve handwheel had stiff rotational resistance during manual bypass operation. Valve was successfully closed by hand with extra torque applied.',
        actual_outcome: 'Work order raised for grease lubrication.',
        expected_sif: 'NEEDS_REVIEW',
        expected_precursors: ['Manual valve actuation mechanical resistance requiring operator force'],
        expected_hazards: ['MECHANICAL'],
        expected_exposure: ['Wellhead skid'],
        expected_barriers: [
          { barrier_name: 'Manual Isolation Valve', status: 'UNKNOWN' },
        ],
        expected_iogp_mapping: ['Energy Isolation'],
        expected_priority: 'MEDIUM',
        annotation_version: 'GOLD_ANN_V1',
        annotator_id: 'user-manish-04',
        annotator_role: 'Site Manager',
        annotator_agreement: 'MAJORITY',
        provenance: 'HUMAN_CURATED',
        is_synthetic: false,
        tags: ['mechanical-integrity', 'ambiguous'],
      },
    ],
  },
  {
    dataset_id: 'ds-regression-suite-v1',
    dataset_version: '1.0.0',
    name: 'SUCHAK Regression & Boundary Suite',
    purpose: 'Regression test suite to catch performance drops in complex narratives, multilingual terminology, and borderline SIF cases.',
    task: 'MULTI_TASK',
    description: '10 boundary condition safety reports testing model robustness across barrier bypass, partial energy isolation, and obscure hazard descriptions.',
    source: 'Phase 9 Human Review Queue Corrections & Field Calibration',
    provenance: 'REVIEW_QUEUE_EXTRACT',
    dataset_type: 'REGRESSION',
    record_count: 10,
    created_at: '2026-07-01T10:00:00Z',
    approved_by: 'Priyanka Saikia (HSE Officer)',
    status: 'ACTIVE',
    class_distribution: {
      sif_potential: 6,
      non_sif_potential: 3,
      needs_review: 1,
    },
    cases: [
      {
        case_id: 'CASE-REG-001',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Rig floor mechanic cleared swarf from rotary table while Kelly bushing was rotating at slow idle (5 RPM). Loose sleeve came in contact with spinning shaft.',
        actual_outcome: 'Shirt sleeve torn away. Zero flesh laceration.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Working adjacent to unshielded rotating drill string machinery with entanglement exposure'],
        expected_hazards: ['MECHANICAL', 'LINE_OF_FIRE'],
        expected_exposure: ['Rotary table pinch point'],
        expected_barriers: [
          { barrier_name: 'Machine Guard Barrier', status: 'BYPASSED' },
        ],
        expected_iogp_mapping: ['Line of Fire'],
        expected_priority: 'CRITICAL',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-priyanka-02',
        annotator_role: 'HSE Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['entanglement', 'rotary-table', 'regression'],
      },
      {
        case_id: 'CASE-REG-002',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Nitrogen purging line quick-connect coupling blew free at 80 psi during pipeline pigging commissioning. Flying coupling struck barrier plywood sheet 1 meter from helper.',
        actual_outcome: 'Impact punched hole in plywood. Zero bodily impact.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Pneumatic pressure coupling detachment creating high-velocity projectile'],
        expected_hazards: ['PRESSURE', 'LINE_OF_FIRE'],
        expected_exposure: ['Nitrogen manifold zone'],
        expected_barriers: [
          { barrier_name: 'Whip Check Restraint', status: 'FAILED' },
        ],
        expected_iogp_mapping: ['Energy Isolation', 'Line of Fire'],
        expected_priority: 'CRITICAL',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-alok-01',
        annotator_role: 'Chief Safety Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['nitrogen', 'pressure', 'projectile'],
      },
      {
        case_id: 'CASE-REG-003',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Scaffold toe-board missing on north deck face 40 feet above concrete hardstand. Heavy pipe wrench placed on scaffold edge vibrated by diesel generator.',
        actual_outcome: 'Tool retrieved by rigger before dropping.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Dropped object risk at height with compromised toe-board containment barrier'],
        expected_hazards: ['GRAVITY'],
        expected_exposure: ['Hardstand pathway below scaffold'],
        expected_barriers: [
          { barrier_name: 'Scaffold Toe-Board Barrier', status: 'FAILED' },
          { barrier_name: 'Tool Tethering Lanyard', status: 'BYPASSED' },
        ],
        expected_iogp_mapping: ['Work at Height'],
        expected_priority: 'HIGH',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['dropped-object', 'scaffold', 'height'],
      },
      {
        case_id: 'CASE-REG-004',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Drinking water dispenser in control room recreation lounge was dripping onto rubber floor mat. Maintenance ticket logged for seal swap.',
        actual_outcome: 'Mat replaced and water turned off.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: [],
        expected_hazards: [],
        expected_exposure: [],
        expected_barriers: [],
        expected_iogp_mapping: [],
        expected_priority: 'LOW',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['facility', 'low-risk'],
      },
      {
        case_id: 'CASE-REG-005',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Radio communication crackle between banksman and crane operator during blind lift of casing elevator. Banksman immediately signaled emergency stop via air horn.',
        actual_outcome: 'Radio swapped for backup handset; lift completed without incident.',
        expected_sif: 'NEEDS_REVIEW',
        expected_precursors: ['Loss of primary radio communication during critical blind tandem crane lift'],
        expected_hazards: ['MECHANICAL'],
        expected_exposure: ['Drill floor casing racks'],
        expected_barriers: [
          { barrier_name: 'Continuous Radio Communication Link', status: 'FAILED' },
          { barrier_name: 'Emergency Horn Signal Protocol', status: 'FUNCTIONING' },
        ],
        expected_iogp_mapping: ['Lifting Operations'],
        expected_priority: 'MEDIUM',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-priyanka-02',
        annotator_role: 'HSE Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['radio', 'lifting', 'communication'],
      },
      {
        case_id: 'CASE-REG-006',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Driver of 20,000L crude tanker truck fell asleep for 2 seconds on highway approach curve. Vehicle tires crossed centerline into oncoming logging truck lane.',
        actual_outcome: 'Rumble strips alerted driver. Swerved back safely.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Heavy bulk hydrocarbon transport driver fatigue resulting in lane departure'],
        expected_hazards: ['TRAFFIC'],
        expected_exposure: ['Public arterial transit road'],
        expected_barriers: [
          { barrier_name: 'Driver Fatigue Monitoring & Rest Policy', status: 'FAILED' },
        ],
        expected_iogp_mapping: ['Driving'],
        expected_priority: 'CRITICAL',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-manish-04',
        annotator_role: 'Site Manager',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['driving', 'tanker', 'fatigue'],
      },
      {
        case_id: 'CASE-REG-007',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Mud engineer reported strong hydrogen sulfide (H2S) alert (25 ppm) on shaker deck. Windsock showed wind blowing toward mud logging cabin where door was propped open.',
        actual_outcome: 'Auto deluge triggered, alarm sounded. Cabin evacuated.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Toxic H2S gas ingress into positive pressure occupied accommodation enclosure'],
        expected_hazards: ['HAZARDOUS_ATMOSPHERE', 'TOXIC_GAS'],
        expected_exposure: ['Mud logging cabin interior and shale shaker house'],
        expected_barriers: [
          { barrier_name: 'Cabin Positive Pressure Air Seal', status: 'BYPASSED' },
        ],
        expected_iogp_mapping: ['Toxic Gas Exposure', 'Confined Space'],
        expected_priority: 'CRITICAL',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-alok-01',
        annotator_role: 'Chief Safety Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['h2s', 'toxic-gas', 'critical'],
      },
      {
        case_id: 'CASE-REG-008',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Loose gravel found scattered on external asphalt walking path near gatehouse. Foot traffic slow and path well lit.',
        actual_outcome: 'Swept by gate security personnel.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: [],
        expected_hazards: [],
        expected_exposure: [],
        expected_barriers: [],
        expected_iogp_mapping: [],
        expected_priority: 'LOW',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['housekeeping', 'low-risk'],
      },
      {
        case_id: 'CASE-REG-009',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'During rig mast lowering operation, crown block wireline snagged on derrick leg diagonal brace. Hydraulic cylinder pressure spiked to relief valve setting.',
        actual_outcome: 'Mast lowering halted immediately. Snag freed manually with come-along hoist.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Structural rigging hang-up during hydraulic mast handling causing severe bending moment'],
        expected_hazards: ['MECHANICAL', 'PRESSURE', 'GRAVITY'],
        expected_exposure: ['Derrick substructure collapse zone'],
        expected_barriers: [
          { barrier_name: 'Mast Travel Clearance Sighting Protocol', status: 'FAILED' },
        ],
        expected_iogp_mapping: ['Lifting Operations', 'Line of Fire'],
        expected_priority: 'CRITICAL',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-alok-01',
        annotator_role: 'Chief Safety Officer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['rig-move', 'mast', 'hydraulic', 'critical'],
      },
      {
        case_id: 'CASE-REG-010',
        dataset_id: 'ds-regression-suite-v1',
        input_text: 'Empty 20-liter lube oil drum was tipped on side in chemical containment berm. Drum was completely dry with zero residual oil.',
        actual_outcome: 'Placed upright and stacked in scrap metal staging bin.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: [],
        expected_hazards: [],
        expected_exposure: [],
        expected_barriers: [],
        expected_iogp_mapping: [],
        expected_priority: 'LOW',
        annotation_version: 'REG_ANN_V1',
        annotator_id: 'user-debajit-03',
        annotator_role: 'Safety Reviewer',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'REVIEW_QUEUE_EXTRACT',
        is_synthetic: false,
        tags: ['waste', 'low-risk'],
      },
    ],
  },
  {
    dataset_id: 'ds-synthetic-smoke-v1',
    dataset_version: '1.0.0',
    name: 'Synthetic Functional Smoke Benchmark [DEMO]',
    purpose: 'Rapid functional verification of evaluation runner, schema parsing, and quality gate triggers.',
    task: 'MULTI_TASK',
    description: '6 synthetic test records clearly designated as simulated test fixtures. NOT intended as empirical proof of operational model accuracy.',
    source: 'Automated Test Harness Generation Engine',
    provenance: 'SYNTHETIC_DEMO',
    dataset_type: 'RELEASE_TEST',
    record_count: 6,
    created_at: '2026-08-01T12:00:00Z',
    approved_by: 'QA Automation Pipeline',
    status: 'ACTIVE',
    class_distribution: {
      sif_potential: 3,
      non_sif_potential: 2,
      needs_review: 1,
    },
    cases: [
      {
        case_id: 'CASE-SYNTH-001',
        dataset_id: 'ds-synthetic-smoke-v1',
        input_text: '[SYNTHETIC TEST CASE] High pressure gas pipeline test manifold bypassed safety relief pop-off valve at 5000 psi.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['High-pressure line testing with bypassed safety restraint'],
        expected_hazards: ['PRESSURE', 'LINE_OF_FIRE'],
        expected_exposure: ['Manifold test perimeter'],
        expected_barriers: [{ barrier_name: 'Safety Relief Valve', status: 'BYPASSED' }],
        expected_iogp_mapping: ['Line of Fire', 'Energy Isolation'],
        expected_priority: 'CRITICAL',
        annotation_version: 'SYNTH_V1',
        annotator_id: 'qa-synthetic-bot',
        annotator_role: 'Test Generator',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'SYNTHETIC_DEMO',
        is_synthetic: true,
        tags: ['synthetic', 'pressure'],
      },
      {
        case_id: 'CASE-SYNTH-002',
        dataset_id: 'ds-synthetic-smoke-v1',
        input_text: '[SYNTHETIC TEST CASE] Scaffold plank missing secure tie wire at elevation 15 meters on drilling rig derrick.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Elevated work without verified primary fall protection barrier'],
        expected_hazards: ['GRAVITY'],
        expected_exposure: ['Derrick elevation'],
        expected_barriers: [{ barrier_name: 'Scaffold Plank Anchor Wire', status: 'FAILED' }],
        expected_iogp_mapping: ['Work at Height'],
        expected_priority: 'HIGH',
        annotation_version: 'SYNTH_V1',
        annotator_id: 'qa-synthetic-bot',
        annotator_role: 'Test Generator',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'SYNTHETIC_DEMO',
        is_synthetic: true,
        tags: ['synthetic', 'height'],
      },
      {
        case_id: 'CASE-SYNTH-003',
        dataset_id: 'ds-synthetic-smoke-v1',
        input_text: '[SYNTHETIC TEST CASE] Confined space entry into separator vessel without calibrated gas monitor or standby attendant.',
        expected_sif: 'SIF_POTENTIAL',
        expected_precursors: ['Confined space entry without verified atmospheric monitoring'],
        expected_hazards: ['HAZARDOUS_ATMOSPHERE', 'TOXIC_GAS'],
        expected_exposure: ['Separator vessel'],
        expected_barriers: [{ barrier_name: 'Standby Rescue Attendant', status: 'BYPASSED' }],
        expected_iogp_mapping: ['Confined Space'],
        expected_priority: 'CRITICAL',
        annotation_version: 'SYNTH_V1',
        annotator_id: 'qa-synthetic-bot',
        annotator_role: 'Test Generator',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'SYNTHETIC_DEMO',
        is_synthetic: true,
        tags: ['synthetic', 'confined-space'],
      },
      {
        case_id: 'CASE-SYNTH-004',
        dataset_id: 'ds-synthetic-smoke-v1',
        input_text: '[SYNTHETIC TEST CASE] Office stationery cabinet door hinges squeaking upon opening. Harmless condition.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: [],
        expected_hazards: [],
        expected_exposure: [],
        expected_barriers: [],
        expected_iogp_mapping: [],
        expected_priority: 'LOW',
        annotation_version: 'SYNTH_V1',
        annotator_id: 'qa-synthetic-bot',
        annotator_role: 'Test Generator',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'SYNTHETIC_DEMO',
        is_synthetic: true,
        tags: ['synthetic', 'low-risk'],
      },
      {
        case_id: 'CASE-SYNTH-005',
        dataset_id: 'ds-synthetic-smoke-v1',
        input_text: '[SYNTHETIC TEST CASE] Water cooler puddle mopped and warning cone placed properly on tile hallway.',
        expected_sif: 'NON_SIF_POTENTIAL',
        expected_precursors: [],
        expected_hazards: [],
        expected_exposure: [],
        expected_barriers: [],
        expected_iogp_mapping: [],
        expected_priority: 'LOW',
        annotation_version: 'SYNTH_V1',
        annotator_id: 'qa-synthetic-bot',
        annotator_role: 'Test Generator',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'SYNTHETIC_DEMO',
        is_synthetic: true,
        tags: ['synthetic', 'low-risk'],
      },
      {
        case_id: 'CASE-SYNTH-006',
        dataset_id: 'ds-synthetic-smoke-v1',
        input_text: '[SYNTHETIC TEST CASE] Unidentified odor noted near compressor skid during shift change. Needs HSE gas check.',
        expected_sif: 'NEEDS_REVIEW',
        expected_precursors: ['Unconfirmed vapor presence near rotating machinery'],
        expected_hazards: ['HAZARDOUS_ATMOSPHERE'],
        expected_exposure: ['Compressor bay'],
        expected_barriers: [{ barrier_name: 'Perimeter Gas Sensor', status: 'UNKNOWN' }],
        expected_iogp_mapping: ['Line of Fire'],
        expected_priority: 'MEDIUM',
        annotation_version: 'SYNTH_V1',
        annotator_id: 'qa-synthetic-bot',
        annotator_role: 'Test Generator',
        annotator_agreement: 'FULL_CONSENSUS',
        provenance: 'SYNTHETIC_DEMO',
        is_synthetic: true,
        tags: ['synthetic', 'ambiguous'],
      },
    ],
  },
];
